### ISSUE TITLE
Where do the CREATE nodes/tables & migrations reside?

### ISSUE THREAD

**Issue by Dorfeuheinz** [florinpatrascu/bolt_movies_elixir_phoenix#3]
I wanted to know how did you create the movies node & where is the schema & migrations file. If that could be made available Id be extremely obliged. Thankyou

**Comment by florinpatrascu** [comment]
Oh, it is or at least it was, included with every Neo4j distribution. Just type `:PLAY movies` and run it, in console after you start the server.

**Comment by Dorfeuheinz** [comment]
No, perhaps I didnt frame my question right. There must be an elixir file with the schema of a particular node that can be used with ecto for changesets & schema, regardless of it being a nosql db involved. Wanted to see how a schema maps to an underlying data store

**Comment by florinpatrascu** [comment]
Unfortunately you'll not find anything like that. 

While you'll see various attempts to create a bridge between sql and nosql data servers, (GitHub hosts a few projects like those), those attempts are simply intellectual exercises done for fun or for satisfying one's curiosity =)

Ecto, and you can say this is my own opinion if you wish, was not designed and not sure if it will ever be, for  addressing the type of concerns you're referring to, I am sorry.

**Comment by Dorfeuheinz** [comment]
I agree with you, since nosql is not as general as sql. Thankyou for your reply sir. Tho devs generally prefer to still use ecto with nosql becoz of the schema & changesets features, while skipping on using ecto_sql. Thats why the 2 have been divided. Its fine tho, i appreciate your efforts. Thankyou
